/**
 * Build-time script: reads all markdown files from docs-site/docs/ and generates
 * src/resources/docsData.generated.ts with inlined content.
 *
 * This ensures the MCP server works via npx without filesystem dependencies at runtime.
 *
 * Set DOCS_ROOT env var to override the default docs location.
 */
import fs from 'node:fs';
import path from 'node:path';

const DOCS_ROOT = process.env.DOCS_ROOT
  ? path.resolve(process.env.DOCS_ROOT)
  : path.resolve(import.meta.dirname, '../../docs-site/docs');
const OUTPUT_FILE = path.resolve(import.meta.dirname, '../src/resources/docsData.generated.ts');

interface DocEntry {
  uri: string;
  title: string;
  content: string;
}

function stripFrontmatter(raw: string): { title: string; content: string } {
  const fmMatch = raw.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!fmMatch) {
    return { title: '', content: raw };
  }

  const frontmatter = fmMatch[1];
  const content = fmMatch[2].trim();

  // Extract title from frontmatter
  const titleMatch = frontmatter.match(/^title:\s*(.+)$/m);
  const title = titleMatch ? titleMatch[1].trim() : '';

  return { title, content };
}

function walk(dir: string, base: string = ''): DocEntry[] {
  const entries: DocEntry[] = [];

  for (const item of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, item.name);

    if (item.isDirectory()) {
      entries.push(...walk(fullPath, base ? `${base}/${item.name}` : item.name));
    } else if (item.name.endsWith('.md')) {
      const raw = fs.readFileSync(fullPath, 'utf-8');
      const { title, content } = stripFrontmatter(raw);
      const slug = item.name.replace(/\.md$/, '');
      const uri = base ? `bind://docs/${base}/${slug}` : `bind://docs/${slug}`;

      entries.push({ uri, title, content });
    }
  }

  return entries;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

const docs = walk(DOCS_ROOT);

const lines = [
  '// AUTO-GENERATED by scripts/bundle-docs.ts — do not edit manually',
  '',
  'export interface DocEntry { uri: string; title: string; content: string; }',
  '',
  'export const docs: DocEntry[] = [',
];

for (const doc of docs) {
  lines.push('  {');
  lines.push(`    uri: ${JSON.stringify(doc.uri)},`);
  lines.push(`    title: ${JSON.stringify(doc.title)},`);
  lines.push(`    content: ${JSON.stringify(doc.content)},`);
  lines.push('  },');
}

lines.push('];');
lines.push('');

// Ensure output directory exists
fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
fs.writeFileSync(OUTPUT_FILE, lines.join('\n'), 'utf-8');

// eslint-disable-next-line no-console
console.log(`Bundled ${docs.length} docs into ${OUTPUT_FILE}`);
